from enum import Enum


class WebsocketType(Enum):
    PROFILE_ADDED = 'PROFILE_ADDED'
    PROFILE_EDITED = 'PROFILE_EDITED'
    PROFILE_DELETED = 'PROFILE_DELETED'
    ANALYSIS_MADE = 'ANALYSIS_MADE'
    POST_ADDED = 'POST_ADDED'
    POST_EDITED = 'POST_EDITED'
    POST_DELETED = 'POST_DELETED'
    USER_ACCOUNT_DELETED = 'USER_ACCOUNT_DELETED'
