from enum import Enum


# ADD str TO ENUM SO PYDANTIC KNOWS HOW TO CONVERT A JSON FORMAT TO THIS ENUM

class BigFiveModelType(str, Enum):
    OPENNESS = "OPENNESS"
    CONSCIENTIOUSNESS = "CONSCIENTIOUSNESS"
    EXTRAVERSION = "EXTRAVERSION"
    AGREEABLENESS = "AGREEABLENESS"
    NEUROTICISM = "NEUROTICISM"
