from enum import Enum


# ADD str TO ENUM SO PYDANTIC KNOWS HOW TO CONVERT A JSON FORMAT TO THIS ENUM

class HobbyType(str, Enum):
    RUNNING = "RUNNING"
    GYM = "GYM"
    READING = "READING"
    TRAVELLING = "TRAVELLING"
    LEARNING = "LEARNING"
    SWIMMING = "SWIMMING"
    COMPUTER_GAMES = "COMPUTER_GAMES"
    LISTENING_TO_MUSIC = "LISTENING_TO_MUSIC"
    WATCHING_MOVIES = "WATCHING_MOVIES"
    YOGA = "YOGA"
    MEDITATION = "MEDITATION"
    DANCING = "DANCING"
    PAINTING = "PAINTING"
    PHOTOGRAPHY = "PHOTOGRAPHY"
    HIKING = "HIKING"
    COOKING = "COOKING"
    CYCLING = "CYCLING"
    WRITING = "WRITING"
    CODING = "CODING"
    VOLUNTEERING = "VOLUNTEERING"
