from enum import Enum


# ADD str TO ENUM SO PYDANTIC KNOWS HOW TO CONVERT A JSON FORMAT TO THIS ENUM
class PersonalityType(str, Enum):
    INTROVERT = "INTROVERT"
    EXTROVERT = "EXTROVERT"
    CREATIVE = "CREATIVE"
    REALISTIC = "REALISTIC"
    EMPATHIC = "EMPATHIC"
    OPTIMISTIC = "OPTIMISTIC"
    PESSIMISTIC = "PESSIMISTIC"
    SPONTANEOUS = "SPONTANEOUS"
    ORGANIZED = "ORGANIZED"
    AMBITIOUS = "AMBITIOUS"
    CURIOUS = "CURIOUS"
    ADVENTUROUS = "ADVENTUROUS"
    OBSERVANT = "OBSERVANT"
    FUNNY = "FUNNY"
    CONFIDENT = "CONFIDENT"
