from enum import Enum


class BigFiveModelType(str, Enum):
    OPENNESS = "OPENNESS"
    CONSCIENTIOUSNESS = "CONSCIENTIOUSNESS"
    EXTRAVERSION = "EXTRAVERSION"
    AGREEABLENESS = "AGREEABLENESS"
    NEUROTICISM = "NEUROTICISM"
