from enum import Enum


# ADD str TO ENUM SO PYDANTIC KNOWS HOW TO CONVERT A JSON FORMAT TO THIS ENUM
class GeneralEmotionType(str, Enum):
    SAD = "SAD"
    HAPPY = "HAPPY"
    ANGRY = "ANGRY"
    EXCITED = "EXCITED"
    MOTIVATED = "MOTIVATED"
    RELAXED = "RELAXED"
    STRESSED = "STRESSED"
    LONELY = "LONELY"
    BORED = "BORED"
    CONFUSED = "CONFUSED"
    ANXIOUS = "ANXIOUS"
