from enum import Enum


# ADD str TO ENUM SO PYDANTIC KNOWS HOW TO CONVERT A JSON FORMAT TO THIS ENUM

class InterestDomainType(str, Enum):
    ARTS = "ARTS"
    HEALTH_CARE = "HEALTH_CARE"
    BUSINESS = "BUSINESS"
    SCIENCE = "SCIENCE"
    RELATIONSHIPS = "RELATIONSHIPS"
    NATURE = "NATURE"
    BOOKS = "BOOKS"
    TECHNOLOGY = "TECHNOLOGY"
    PSYCHOLOGY = "PSYCHOLOGY"
    EDUCATION = "EDUCATION"
    FINANCE = "FINANCE"
    SPORTS = "SPORTS"
    ENTERTAINMENT = "ENTERTAINMENT"
    ENVIRONMENT = "ENVIRONMENT"
    PHILOSOPHY = "PHILOSOPHY"
    POLITICS = "POLITICS"
    ASTRONOMY = "ASTRONOMY"
    HISTORY = "HISTORY"
    RELIGION = "RELIGION"
    FASHION = "FASHION"
    SELF_DEVELOPMENT = "SELF_DEVELOPMENT"
    GAMING = "GAMING"
    FOOD = "FOOD"
